# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/underwater-systems',
                'doc_host': 'https://andreamunafo.github.io',
                'git_url': 'https://github.com/andreamunafo/underwater-systems',
                'lib_path': 'underwater_systems'},
  'syms': {'underwater_systems.core': {'underwater_systems.core.foo': ('core.html#foo', 'underwater_systems/core.py')}}}
